version: '3'

set:
  - errexit
  - nounset
  - pipefail

output: 'group'

includes:
  cert-manager: tasks/cert-manager.yaml
  kcp: tasks/kcp.yaml
  kind: tasks/kind.yaml
  reflector: tasks/reflector.yaml
  capi: tasks/capi.yaml

env:
  KUBECONFIG: "{{.KIND_CLUSTER_NAME}}-kind.kubeconfig"
  KCP_ADMIN_EXTERNAL_KUBECONFIG: "kcp-admin.kubeconfig"

tasks:
  run-demo:
    desc: Run the demo
    vars:
      CONSUMER_WORKSPACE: tenant-a
    cmds:
      - task: kind:create
      - task: cert-manager:deploy
      - task: deploy-required-apps
      - task: cert-manager:publish-api
      - task: kcp:create-workspace
        vars:
          WORKSPACE: '{{.CONSUMER_WORKSPACE}}'
      - task: cert-manager:create-apibinding
        vars:
          WORKSPACE: '{{.CONSUMER_WORKSPACE}}'

  deploy-required-apps:
    deps: [reflector:deploy, capi:init, kcp:deploy]
    internal: true

  cleanup:
    desc: Cleanup the demo environment
    cmds:
      - rm -f "${KCP_ADMIN_EXTERNAL_KUBECONFIG}"
      - task: kind:delete
