version: '3'

set:
  - errexit
  - nounset
  - pipefail

includes:
  cert-manager: tasks/cert-manager.yaml
  kcp: tasks/kcp.yaml
  kind: tasks/kind.yaml
  reflector: tasks/reflector.yaml

tasks:
  run-demo:
    desc: Run the demo
    cmds:
      - task: kind:create
      - task: cert-manager:deploy
      - task: reflector:deploy
      - task: kcp:deploy

  cleanup:
    desc: Cleanup the demo environment
    cmds:
      - task: kind:delete
