version: '3'

set:
  - errexit
  - nounset
  - pipefail

includes:
  cert-manager: tasks/cert-manager.yaml
  kcp: tasks/kcp.yaml
  kind: tasks/kind.yaml
  reflector: tasks/reflector.yaml
  apis: tasks/apis.yaml

env:
  KUBECONFIG: "{{.KIND_CLUSTER_NAME}}-kind.kubeconfig"
  KCP_ADMIN_KUBECONFIG: "kcp-admin.kubeconfig"

tasks:
  run-demo:
    desc: Run the demo
    cmds:
      - task: kind:create
      - task: cert-manager:deploy
      - task: reflector:deploy
      - task: kcp:deploy
      - task: apis:capi-apigen
      - task: kcp:create-capi-api-provider
      - task: kcp:create-capi-api-consumer

  cleanup:
    desc: Cleanup the demo environment
    cmds:
      - task: kind:delete
