version: 3

vars:
  CAPI_CRDS_DIR: "./config/apis/capi/crds"
  CAPI_APIEXPORTS_DIR: "./config/apis/capi/exports"

tasks:
  capi-apigen:
    desc: Generate CAPI API exports
    cmds:
      - task: capi-kustomize-crds
      - rm -rf "{{.CAPI_APIEXPORTS_DIR}}"
      - mkdir -p "{{.CAPI_APIEXPORTS_DIR}}"
      - apigen --input-dir "{{.CAPI_CRDS_DIR}}" --output-dir "{{.CAPI_APIEXPORTS_DIR}}"

  capi-kustomize-crds:
    internal: true
    cmds:
      - rm -rf "{{.CAPI_CRDS_DIR}}"
      - mkdir -p "{{.CAPI_CRDS_DIR}}"
      - kustomize build https://github.com/kubernetes-sigs/cluster-api/config/crd?ref=v1.10.3 |
          yq 'del(.spec.conversion) | del(.spec.versions[] | select(.storage == false))'
            --split-exp '"{{.CAPI_CRDS_DIR}}/" + .spec.group + "_" + (.spec.names.kind | downcase) + ".yaml"' --no-doc
