# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: '3'

env:
  CLUSTER_TOPOLOGY: true

tasks:
  init:
    cmds:
      - clusterctl init --infrastructure=docker
    status:
      - kubectl get namespace capd-system &>/dev/null
