version: 3

tasks:
  deploy:
    desc: Deploy KCP
    cmds:
      - task: deploy-kcp
      - task: generate-kcp-admin-kubeconfig

  deploy-kcp:
    internal: true
    cmds:
      - helm upgrade --install kcp kcp --repo=https://kcp-dev.github.io/helm-charts
          --namespace=kcp --create-namespace
          --values=config/kcp-values.yaml
          --wait --wait-for-jobs
    sources:
      - config/kcp-values.yaml
    status:
      - "helm status --namespace=kcp kcp | grep --quiet '^STATUS: deployed$'"

  generate-kcp-admin-kubeconfig:
    desc: Generate KCP admin kubeconfig
    env:
      external_hostname:
        sh: helm get values -n kcp kcp -o yaml | gojq --yaml-input --raw-output '.externalHostname'
    cmds:
      - envsubst --no-unset --no-digit --no-empty -i config/kcp-admin-kubeconfig.tmpl -o kcp-admin.kubeconfig
    sources:
      - config/kcp-admin-kubeconfig.tmpl
    generates:
      - kcp-admin.kubeconfig
    preconditions:
      - "helm status --namespace=kcp kcp | grep --quiet '^STATUS: deployed$'"
