# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: '3'

vars:
  KIND_CLUSTER_NAME: kcp-capi

tasks:
  create:
    desc: Ensure KinD cluster is running
    cmds:
      - task: create-kind
      - task: deploy-cilium

  create-kind:
    internal: true
    run: once
    vars:
      K8S_VERSION:
        sh: crane ls ghcr.io/mesosphere/kind-node | grep --invert-match 64 | sort --reverse --version-sort | head -1
    cmds:
      - kind create cluster --name '{{.KIND_CLUSTER_NAME}}'
        --image 'ghcr.io/mesosphere/kind-node:{{.K8S_VERSION}}' --config=<(envsubst -i config/kind-config.yaml)
    status:
      - kind get clusters | grep --quiet '^{{.KIND_CLUSTER_NAME}}$'

  deploy-gateway-api-crds:
    internal: true
    run: once
    cmds:
      - kubectl apply --server-side
          --filename=https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml
    status:
      - kubectl get
          --filename=https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/experimental-install.yaml &>/dev/null

  deploy-cilium:
    internal: true
    run: once
    deps:
      - deploy-gateway-api-crds
    cmds:
      - helm upgrade --install cilium cilium --repo=https://helm.cilium.io
          --namespace=kube-system --create-namespace
          --values=config/cilium-values.yaml
          --wait --wait-for-jobs
          --hide-notes
      - kubectl apply --server-side --filename=config/hubble-ui-gateway.yaml
    sources:
      - config/cilium-values.yaml
    status:
      - "helm status --namespace=kube-system cilium | grep --quiet '^STATUS: deployed$'"
      - kubectl get --filename=config/hubble-ui-gateway.yaml &>/dev/null

  delete:
    desc: Delete KinD cluster
    cmds:
      - kind delete cluster --name '{{.KIND_CLUSTER_NAME}}'
      - rm --force "${KUBECONFIG}"
    preconditions:
      - kind get clusters | grep --quiet '^{{.KIND_CLUSTER_NAME}}$'
