fullnameOverride: beta
externalHostname: "kcp.127.0.0.1.sslip.io"
externalPort: 8443
certificates:
  dnsNames:
  - localhost
  - beta.kcp-beta
  - beta.kcp-beta.svc
  - beta.kcp-beta.svc.cluster.local
  kcp:
    pki: false
    certs: true
  frontproxy:
    pki: false
    certs: false
  etcd:
    pki: false
    certs: true
  cache:
    pki: false
    certs: false
  secretTemplate:
    enabled: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kcp-alpha,kcp-beta,kcp-proxy,kcp-cache"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kcp-alpha,kcp-beta,kcp-proxy,kcp-cache"
