fullnameOverride: alpha
externalHostname: "kcp.127.0.0.1.sslip.io"
externalPort: 8443
etcd:
  enabled: true
kcp:
  enabled: true
  externalLogicalClusterAdminFlag: true
  tag: v0.27.1
  v: 8
  tokenAuth:
    enabled: true
  batteries:
    - workspace-types
    - metrics-viewer
  extraFlags:
  - --feature-gates=WorkspaceMounts=true
  homeWorkspaces:
    enabled: true
  resources: null
  hostAliases:
    enabled: true
    values:
      - ip: "10.96.0.100"
        hostnames:
          - "kcp.127.0.0.1.sslip.io"
externalCache:
  enabled: true
  cacheInternalHostname: "cache-cache.kcp-cache.svc"
sharding:
  enabled: true
  isRoot: true
